[workspace]
members = [
    "warthog_wow",
    "warthog_lib",
    "warthog_messages",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.36.0", features = ["full"] }

[workspace.lints.rust]
unused_must_use = "deny"
